### ISSUE TITLE
0.0.155 broke highlighting

### ISSUE THREAD

**Issue by unai-ndz** [Gruntfuggly/todo-tree#224]
Tag detection in the tree is working as expected
My config (with corresponding `highlights.customHighlight` and `general.tags`):

 ```json
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|--)\\s*(TODO|FIXME|!TODO| \\?| \\^|\\+)|^\\s*- \\[ \\])"
```

Changing it to:

```json
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|--)\\s*($TAGS)|^\\s*- \\[ \\])",
```
Fixes the highlighting but breaks the tag detection in the tree.

**Comment by Gruntfuggly** [comment]
Can you post an example of the tags it should match.

**Comment by unai-ndz** [comment]
```json
"todo-tree.highlights.customHighlight": {
        "TODO": {
          "icon": "alert",
          "type": "tag",
          "foreground": "yellow",
          "background": "yellow",
        },
        "FIXME": {
          "icon": "alert",
          "type": "tag",
          "foreground": "orange",
          "background": "orange",
        },
        "!TODO": {
          "icon": "alert",
          "type": "tag",
          "foreground": "red",
          "background": "red",
        },
        " \\?": {
          "icon": "alert",
          "type": "text",
          "foreground": "blue",
        },
        " \\^": {
          "type": "line",
          "foreground": "green",
          "hideFromTree": true,
        },
        "\\+": {
          "type": "tag",
          "foreground": "yellow",
          "hideFromTree": true,
        }
    },
    "todo-tree.filtering.passGlobsToRipgrep": false,
    "todo-tree.general.tags": [
      "TODO",
      "FIXME",
      "!TODO",
      " \\?",
      " \\^",
      "\\+"
    ],
```

```json
      // TODO Some comment
      // FIXME Some comment
      // !TODO Some comment
      // ? Should I reformat this?
      // ^ Some comment
      //+ Some comment
```

**Comment by Gruntfuggly** [comment]
Did this ever work properly with previous versions?

**Comment by torves** [comment]
Had a similar issue with my config
```
"todo-tree.highlights.customHighlight": {
        "TODO": {
            "background": "#ffbd2a"
        },
        "FIXME": {
            "background": "#f06292"
        },
        "NOTE": {
            "background": "#00ffff"
        },
        "BUG": {
            "background": "#ff0000"
        },
        "TEST": {
            "background": "#00ff00"
        }
    },
    "todo-tree.general.tags": [
        "TODO:",
        "FIXME:",
        "NOTE:",
        "BUG:",
        "TEST:"
    ],
```

I had to change the `customHighlight` settings to match the general tags including the colon `:` that had worked previously without. So my custom highlights are now:
```
        "TODO:": {
            "background": "#ffbd2a"
        },
        "FIXME:": {
            "background": "#f06292"
        },
        "NOTE:": {
            "background": "#00ffff"
        },
        "BUG:": {
            "background": "#ff0000"
        },
        "TEST:": {
            "background": "#00ff00"
        }
```

**Comment by Gruntfuggly** [comment]
@torves Was that your previous configuration above? I'm surprised that worked. I would have expected it needed the colon. What's really odd is that the colon isn't a character that is escaped, so there really shouldn't have been any difference.
If you revert the extension to the previous version (from the extensions page) does your original configuration work?

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should fix the highlighting.

The characters in `todo-tree.tags` and `todo-tree.customHighlight` no longer need to be escaped (only the backslash).

So the following should now work as you'd expect:

```
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^|--)\\s*($TAGS)|^\\s*- \\[ \\])",
    "todo-tree.highlights.customHighlight": {
        "TODO": {
            "icon": "alert",
            "type": "tag",
            "foreground": "yellow",
            "background": "yellow",
        },
        "FIXME": {
            "icon": "alert",
            "type": "tag",
            "foreground": "orange",
            "background": "orange",
        },
        "!TODO": {
            "icon": "alert",
            "type": "tag",
            "foreground": "red",
            "background": "red",
        },
        "?": {
            "icon": "alert",
            "type": "text",
            "foreground": "blue",
            "background": "#333"
        },
        "^": {
            "type": "line",
            "foreground": "magenta",
            "background": "#333"
        },
        "TO\\DO": {
            "type": "tag",
            "foreground": "blue",
            "background": "#333"
        }
        "+": {
            "type": "tag",
            "foreground": "blue",
            "background": "#333"
        }
    },
    "todo-tree.general.tags": [
        "TODO",
        "FIXME",
        "!TODO",
        "TO\\DO",
        "?",
        "^",
        "+"
    ]
```

**Comment by unai-ndz** [comment]
@Gruntfuggly
Yes, this works on `0.0.154` and several other versions. Check out #153 and #146

@torves I don't think your issue is related to this.

Well, never mind, you are fast. I noticed the escaping wasn't necessary anymore but the `+` without space before it was still failing. With `0.0.157`  that is fixed too.

Thanks for your work with this extension again.

**Comment by Gruntfuggly** [comment]
Glad it's working!
